# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "0.6"
    - nodejs_version: "0.8"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% EQU 0.8 npm -g install npm@2
  - IF %nodejs_version% EQU 0.8 set PATH=%APPDATA%\npm;%PATH%
  - npm -g install npm
  - IF %nodejs_version% NEQ 0.8 set PATH=%APPDATA%\npm;%PATH%
  # install modules
  - npm install
# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  # run tests
  - npm test

build: off